### ISSUE TITLE
Redirect to original destination after login

### ISSUE THREAD

**Issue by SergioCBPC** [codehaiku/subway-2.0#52]
There should be an option to allow redirection to the intended destination after login. I know in the settings there are a few options to redirect the user to specific pages after login or the default which just stays in the login page, but there should be another option that allows the user to continue to the intended destination after login. For example if a user clicks on a link to a specific group/member or doc page, once logged in, instead of redirecting it to the dashboard page or other predefined page, it should redirect to the intended destination.
I know there are other modules that do this but using them will probably break the functionality of this plugin. Thus, I think this plugin should be able to handle this. 
Do you know of a redirection plugin that will play nice with this plugin?

**Comment by codehaiku** [comment]
Here you go

<img width="910" alt="Screen Shot 2019-09-11 at 3 38 33 AM" src="https://user-images.githubusercontent.com/4960876/64644641-ad7d1b00-d445-11e9-95ff-f1752f792fc8.png">

Please try this
